rename hoh operator CR.
stolostron/hub-of-hubs pull request #115
Opened 2022-08-09 13:22 UTC by morvencao

ref: https://github.com/stolostron/backlog/issues/24609

Signed-off-by: morvencao <lcao@redhat.com>

2022-08-09 14:47 UTC, clyang82 requested changes

2022-08-09 14:47 UTC, clyang82 commented on operator/config/crd/bases/hubofhubs.open-cluster-management.io_multiclusterglobalhubs.yaml
>    group: hubofhubs.open-cluster-management.io
suggest to use `operator.open-cluster-management.io` as group name.

2022-08-09 14:51 UTC, clyang82 commented
fix the code smell. most of them are `which is greater than 120 authorized`. I am looking for a tool to configure in vscode to avoid such error.

2022-08-10 01:19 UTC, morvencao commented on operator/config/crd/bases/hubofhubs.open-cluster-management.io_multiclusterglobalhubs.yaml
>    group: hubofhubs.open-cluster-management.io
done

2022-08-10 03:31 UTC, clyang82 commented
/lgtm

2022-08-10 03:35 UTC, merged