Setup HoH KinD cluster with service-ca and router
stolostron/hub-of-hubs pull request #53
Opened 2022-06-15 16:06 UTC by yanmxa

Signed-off-by: myan <myan@redhat.com>

2022-06-15 16:07 UTC, yanmxa commented
https://github.com/stolostron/backlog/issues/23507

2022-06-15 16:07 UTC, yanmxa commented
/cc @clyang82 @morvencao

2022-06-20 00:54 UTC, clyang82 requested changes

2022-06-20 00:54 UTC, clyang82 commented on test/setup/common.sh
> +    kubectl apply -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/crds.yaml
can you pin to the latest tag?

2022-06-20 00:54 UTC, clyang82 commented on test/setup/hoh_setup.sh
> +enableServiceCA "kind-$HUB_OF_HUB_NAME" "${CURRENT_DIR}/service-ca/" >> "$LOG" 2>&1
maybe you can use this [operator](https://github.com/openshift/service-ca-operator) instead of put the manifests here?

2022-06-20 03:40 UTC, yanmxa commented on test/setup/hoh_setup.sh
> +enableServiceCA "kind-$HUB_OF_HUB_NAME" "${CURRENT_DIR}/service-ca/" >> "$LOG" 2>&1
It seems the [service-ca-operator](https://github.com/openshift/service-ca-operator) doesn't exist in the [community](https://operatorhub.io/).

2022-06-20 03:40 UTC, yanmxa commented on test/setup/common.sh
> +    kubectl apply -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/crds.yaml
sure

2022-06-20 06:18 UTC, clyang82 commented
/lgtm

2022-06-20 06:21 UTC, merged