Enable the postgres for installing hub-of-hubs
stolostron/hub-of-hubs pull request #56
Opened 2022-06-22 04:06 UTC by yanmxa

Signed-off-by: Meng <yanmxa@163.com>

2022-06-22 04:08 UTC, yanmxa commented
https://github.com/stolostron/backlog/issues/23504

2022-06-22 04:09 UTC, yanmxa commented
/cc @clyang82 @morvencao

2022-06-22 14:39 UTC, clyang82 requested changes
This is not a postgres setup. this is

2022-06-22 14:39 UTC, clyang82 commented on test/setup/postgres/postgres_setup.sh
> +
You missed `#!/bin/bash`

2022-06-22 14:39 UTC, clyang82 commented on test/setup/postgres/postgres_setup.sh
> +    deployComponent "hub-of-hubs-postgresql" "$branch" deployHohPostgresqlAction
Do you need to define `branch` or it is passed from parent script?

2022-06-22 14:39 UTC, clyang82 commented on test/setup/postgres/postgres_setup.sh
> +  IMAGE=quay.io/open-cluster-management-hub-of-hubs/postgresql-ansible:$TAG ./setup.sh
That is OK for now. in future, we need to separate the postgres installation and DB init.

2022-06-23 00:34 UTC, clyang82 commented on test/setup/postgres/postgres_setup.sh
> +    deployComponent "hub-of-hubs-postgresql" "$branch" deployHohPostgresqlAction
we may need to have a default value for it.

2022-06-23 00:44 UTC, clyang82 commented on test/setup/postgres/postgres_setup.sh
> +  IMAGE=quay.io/open-cluster-management-hub-of-hubs/postgresql-ansible:$TAG ./setup.sh
maybe we move `https://github.com/stolostron/hub-of-hubs-postgresql/tree/main/pgo/install` here. we do not need to enable HA for tests. WDYT?

2022-06-23 01:49 UTC, yanmxa commented on test/setup/postgres/postgres_setup.sh
> +    deployComponent "hub-of-hubs-postgresql" "$branch" deployHohPostgresqlAction
> Do you need to define `branch` or it is passed from the parent script?

It is passed from the parent script. It's better to set a default value for the branch.

2022-06-23 05:33 UTC, clyang82 commented on test/setup/postgres/postgres_setup.sh
> +  IMAGE=quay.io/open-cluster-management-hub-of-hubs/postgresql-ansible:$TAG
Can you move the init job out of here? It does not belong to postgres setup. it belongs to hoh installation.

2022-06-23 09:00 UTC, clyang82 commented
/lgtm

2022-06-23 09:02 UTC, merged