Enable kafka cluster for installing hub-of-hubs
stolostron/hub-of-hubs pull request #57
Opened 2022-06-22 08:19 UTC by yanmxa

Signed-off-by: Meng <yanmxa@163.com>

2022-06-22 08:20 UTC, yanmxa commented
https://github.com/stolostron/backlog/issues/23505

2022-06-22 08:20 UTC, yanmxa commented
/cc @clyang82 @morvencao

2022-06-22 11:36 UTC, morvencao commented on test/setup/kafka/kafka-operator.yaml
> +  generateName: kafka-
is the `generateName` must-have?

2022-06-23 00:41 UTC, clyang82 requested changes

2022-06-23 00:41 UTC, clyang82 commented on test/setup/kafka/kafka-operator.yaml
> +  channel: strimzi-0.23.x
0.23.x or 0.27.x?

2022-06-23 00:41 UTC, clyang82 commented on test/setup/kafka/kafka_setup.sh
> +
You have missed `#!/bin/bash`

2022-06-23 00:41 UTC, clyang82 commented on test/setup/kafka/kafka_setup.sh
> +  curl -s "https://raw.githubusercontent.com/stolostron/hub-of-hubs-kafka-transport/$branch/deploy/kafka-cluster.yaml" | kubectl apply -f -
Can we move `https://github.com/stolostron/hub-of-hubs-kafka-transport/blob/main/deploy/kafka-cluster.yaml` into this repo? `hub-of-hubs-kafka-transport` may be deprecated in the future.

2022-06-23 00:41 UTC, clyang82 commented on test/setup/kafka/kafka_setup.sh
> +  operatorDeployed=$(kubectl -n kafka get Deployment/strimzi-cluster-operator-v0.23.0 --ignore-not-found)
can we define the version as an environment variable?

2022-06-23 01:16 UTC, yanmxa commented on test/setup/kafka/kafka-operator.yaml
> +  generateName: kafka-
It's not necessary to add the generateName. I think we can remove it from the yaml file. It shouldn't make any difference.

2022-06-23 01:36 UTC, yanmxa commented on test/setup/kafka/kafka_setup.sh
> +  operatorDeployed=$(kubectl -n kafka get Deployment/strimzi-cluster-operator-v0.23.0 --ignore-not-found)
Yeah, I extracted the operator name with a specific version to the environment variable KAFKA_OPERATOR.

2022-06-23 02:05 UTC, clyang82 commented
/lgtm

2022-06-23 02:09 UTC, merged