Deploy HoH in KinD cluster
stolostron/hub-of-hubs pull request #62
Opened 2022-06-28 10:17 UTC by yanmxa

Signed-off-by: myan <myan@redhat.com>

fixes: https://github.com/stolostron/backlog/issues/23506

2022-06-28 15:36 UTC, yanmxa commented
/cc @clyang82 @morvencao

2022-06-28 16:08 UTC, yanmxa commented
## The steps to setup HoH locally
```bash
$ ./test/setup/e2e_setup.sh    
[23:50:02]  ✅  KUBECONFIG=/root/workspace/stolostron/hub-of-hubs/test/setup/config/kubeconfig ...
[23:50:16]  ✅  1 Prepare top hub cluster hub-of-hubs ...
[23:51:12]  ✅    Enable OLM for kind-hub-of-hubs ...
[23:51:17]  ✅    Prepare top hub cluster dependency resources ...
[23:51:17]  ✅  2 Prepare leaf hub cluster hub1
[23:51:18]  ✅    Leaf Hub: export KUBECONFIG=/root/workspace/stolostron/hub-of-hubs/test/setup/config/kubeconfig ...
[23:51:33]  ✅    Create KinD Cluster hub1 ...
[23:51:49]  ✅    Create KinD Cluster hub1-cluster1 ...
[23:52:04]  ✅    Create KinD Cluster hub1-cluster2 ...
[23:52:32]  ✅    OCM init hub kind-hub1 ...
[23:52:56]  ✅    OCM join managed kind-hub1-cluster1 ...
[23:53:20]  ✅    OCM join managed kind-hub1-cluster2 ...
[23:54:30]  ✅    Application hub1-cluster1 ...
[23:55:21]  ✅    Application hub1-cluster2 ...
[23:56:08]  ✅    Policy hub1-cluster1 ...
[23:56:48]  ✅    Policy hub1-cluster2 ...
[23:57:27]  ✅  3 Join LH to HoH hub-of-hubs - hub1 ...
[23:57:35]  ✅    Joining kind-hub-of-hubs - kind-hub1 ...
[23:58:45]  ✅    Enable application kind-hub-of-hubs - kind-hub1 ...
[23:59:41]  ✅    Enable Policy kind-hub-of-hubs - kind-hub1 ...
[00:03:05]  ✅  4 Install kafka cluster ...
[00:03:43]  ✅  5 Install postgres cluster ...
[00:06:39]  ✅  6 Deploy hub-of-hubs ...
[Access the Clusters]: export KUBECONFIG=/root/workspace/stolostron/hub-of-hubs/test/setup/config/kubeconfig
```

2022-06-29 02:42 UTC, clyang82 requested changes

2022-06-29 02:42 UTC, clyang82 commented on agent/pkg/helper/config.go
> +	pflag.StringVar(&configManager.Kafka.BootstrapServers, "kafka-bootstrap-server", "kafka-brokers-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092", "The bootstrap server for kafka.")
This value is not correct. We won't install Kafka in LH cluster. that is always not true.

2022-06-29 02:42 UTC, clyang82 commented on test/setup/kafka/kafka-cluster.yaml
> +        tls: true
Do you really want to enable `tls` for kafka?

2022-06-29 02:42 UTC, clyang82 commented on test/setup/hoh/hub-of-hubs-operator.yaml
> +---
suggest to rename it to `hub-of-hubs-manager`? we will have operator soon.

2022-06-29 02:42 UTC, clyang82 commented on test/setup/hoh_setup.sh
> +function updateAppAndPolicyImages() {
Suggest to use `patchImages`. it is not only for app and policy. you include placement as well.

2022-06-29 02:42 UTC, clyang82 commented on test/setup/hoh_setup.sh
> +  kubectl apply -f ${currentDir}/hoh/hub-of-hubs-cluster-manager.yaml
Could you share why cannot patch this image?

2022-06-29 02:42 UTC, clyang82 commented on manager/cmd/manager/main.go
> +	pflag.StringVar(&managerConfig.kafkaConfig.bootstrapServer, "kafka-bookstrap-server", "kafka-brokers-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092", "The bootstrap server for kafka.")
is it necessary to add `.cluster.local`?

2022-06-29 02:56 UTC, morvencao commented on manager/cmd/manager/main.go
> +	pflag.StringVar(&managerConfig.kafkaConfig.bootstrapServer, "kafka-bookstrap-server", "kafka-brokers-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092", "The bootstrap server for kafka.")
Better to remove cluster domain `.cluster.local` because it may be configured instesd of default one.

2022-06-29 02:56 UTC, morvencao commented on test/setup/hoh/hub-of-hubs-addon.yaml
> +  verbs: ["get"]
The clusterrole is not the latest one, check https://github.com/stolostron/hub-of-hubs-addon/blob/main/deploy/hub_controller_clusterrole.yaml

2022-06-29 04:39 UTC, yanmxa commented on agent/pkg/helper/config.go
> +	pflag.StringVar(&configManager.Kafka.BootstrapServers, "kafka-bootstrap-server", "kafka-brokers-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092", "The bootstrap server for kafka.")
Yeah. I will keep the default bootstrapserver empty in leafhub.

2022-06-29 04:52 UTC, yanmxa commented on test/setup/kafka/kafka-cluster.yaml
> +        tls: true
There are two reasons that I think it should be true:

1. If we can set the tls to false. That will invoke panic errors in the hub-of-hubs-addon https://github.com/stolostron/hub-of-hubs-addon/blob/fb5e229e436ec81f9109ceace21b3aebe8f6fd14/pkg/agent/controller.go#L315

2. If we modify the hub-of-hubs-addon codebase, which might become incompatible with the origin route type of the kafka service.

2022-06-29 05:02 UTC, yanmxa commented on test/setup/hoh_setup.sh
> +  kubectl apply -f ${currentDir}/hoh/hub-of-hubs-cluster-manager.yaml
Because the image for cluster-manager placement is controlled by the ClusterManager CR. I don't know how to update the value of CR by patching. Thank you very much if you know how to do that！

2022-06-29 05:20 UTC, yanmxa commented on test/setup/hoh/hub-of-hubs-addon.yaml
> +  verbs: ["get"]
@morvencao 
The route is for the external kafka cluster service.  In my opinion, the internal host address with `.cluster.local` is not associated with route service. 

If we config the cluster domain instead of the default one, with or without the suffix `.cluster.local` is going to be the same result.

But we can remove it if you really think that would be better without the suffix `.cluster.local`

2022-06-29 05:23 UTC, yanmxa commented on manager/cmd/manager/main.go
> +	pflag.StringVar(&managerConfig.kafkaConfig.bootstrapServer, "kafka-bookstrap-server", "kafka-brokers-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092", "The bootstrap server for kafka.")
@clyang82 @morvencao 
I checked the Kafka cluster service(both KinD and OCP cluster). And the internal host address with the suffix - `.cluster.local`. As shown below:
```
» oc get kafka kafka-brokers-cluster -n kafka -oyaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
...
status:
  clusterId: -_XB_aGITeeC0VUwxDDxmg
  conditions:
  - lastTransitionTime: "2022-06-28T16:02:54.793Z"
    status: "True"
    type: Ready
  listeners:
  - addresses:
    - host: kafka-brokers-cluster-kafka-bootstrap.kafka.svc.cluster.local
      port: 9092
    bootstrapServers: kafka-brokers-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
    type: plain
  - addresses:
    - host: 172.18.0.2
      port: 30095
    bootstrapServers: 172.18.0.2:30095
    ...
  observedGeneration: 1
```

2022-06-29 05:28 UTC, yanmxa commented on manager/cmd/manager/main.go
> +	pflag.StringVar(&managerConfig.kafkaConfig.bootstrapServer, "kafka-bookstrap-server", "kafka-brokers-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092", "The bootstrap server for kafka.")
This domain is just for internal service. I added it to indicate the svc is just for the local cluster. It's okay to remove it if you think without the suffix is better~

2022-06-29 06:13 UTC, yanmxa commented on test/setup/hoh_setup.sh
> +  kubectl apply -f ${currentDir}/hoh/hub-of-hubs-cluster-manager.yaml
The image need to be update: `oc get clustermanager cluster-manager -o jsonpath='{.spec.placementImagePullSpec}'`

2022-06-29 08:11 UTC, clyang82 commented on test/setup/hoh_setup.sh
> +  kubectl apply -f ${currentDir}/hoh/hub-of-hubs-cluster-manager.yaml
Can you use ` kubectl patch clustermanager Kyk8W-ojJHE-4QTX8-pTYAM ...`?

2022-06-29 08:12 UTC, clyang82 commented on test/setup/kafka/kafka-cluster.yaml
> +        tls: true
You may not mark it as resolved until it is resolved really.

Do you need to provide ca to access kafka?

2022-06-29 09:45 UTC, clyang82 commented on test/setup/hoh_setup.sh
> +  kubectl apply -f ${currentDir}/hoh/hub-of-hubs-cluster-manager.yaml
You can use this command to patch `kubectl patch clustermanager cluster-manager --type merge -p '{"spec":{"placementImagePullSpec":"quay.io/open-cluster-management-hub-of-hubs/placement:hub-of-hubs@sha256:b7293b436dc00506b370762fb4eb352e7c6cc5413d135fc03c93ed311e7ed4c4"}}'`

2022-06-29 12:00 UTC, clyang82 requested changes

2022-06-29 13:25 UTC, yanmxa commented on test/setup/hoh/hub-of-hubs-rbac/secret/role_bindings.yaml
> +      - admin
I happen to have some issues with nonk8s authorization. How about we discuss it tomorrow and decide what to do about it?

2022-06-30 03:20 UTC, clyang82 commented
/lgtm

2022-06-30 03:21 UTC, merged