Test connection and rbac for HoH scenario cases
stolostron/hub-of-hubs pull request #68
Opened 2022-07-04 07:52 UTC by yanmxa

Signed-off-by: myan <myan@redhat.com>

Fixed: https://github.com/stolostron/backlog/issues/24008

2022-07-04 07:55 UTC, yanmxa commented on test/setup/microshift/microshift_setup.sh
> +  until docker cp $clusterName:/var/lib/microshift/resources/kubeadmin/kubeconfig $currentDir/../config/kubeconfig-microshift > /dev/null 2>&1
The `until docker cp ...` script is from @morvencao

2022-07-04 07:56 UTC, yanmxa commented
/cc @clyang82 @morvencao

2022-07-04 10:13 UTC, morvencao commented on test/pkg/test/hoh-client_test.go
> +var _ = Describe("Check all the clients could connect to the HoH servers", Label("connection"), func() {
nit: consider to use `hubClient.Discovery().RESTClient().Get().AbsPath("/healthz").DoRaw()` to check the health of cluster.

2022-07-04 14:44 UTC, yanmxa commented on test/pkg/test/hoh-client_test.go
> +var _ = Describe("Check all the clients could connect to the HoH servers", Label("connection"), func() {
That's a good idea! I added the health check spec in it.

2022-07-05 01:56 UTC, morvencao reviewed
/LGTM

2022-07-05 02:44 UTC, clyang82 requested changes

2022-07-05 02:44 UTC, clyang82 commented on test/setup/hoh/hub-of-hubs-rbac/secret/role_bindings.yaml
> +  "system:masters":
We can remove `kube:admin` since we do not have such user in microshift context.

2022-07-05 03:48 UTC, yanmxa commented
/lgtm

2022-07-05 04:22 UTC, morvencao reviewed
/lgtm

2022-07-05 05:47 UTC, clyang82 commented
/approve

2022-07-05 06:03 UTC, merged